//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchdogDatabaseAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Params { get; set; }
        public int MessageTypeId { get; set; }
        public bool IsProcessed { get; set; }
        public string Server { get; set; }
        public string Origin { get; set; }
    
        public virtual MessageType MessageType { get; set; }
    }
}
