//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchdogDatabaseAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlertStatus()
        {
            this.Timestamp = new DateTime(621355968000000000, DateTimeKind.Unspecified);
        }
    
        public int Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string ModifiedBy { get; set; }
        public StatusCode StatusCode { get; set; }
    
        public virtual AlertStatus Next { get; set; }
        public virtual AlertStatus Prev { get; set; }
        public virtual Alert Alert { get; set; }
    }
}
