//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchdogDatabaseAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertCategoryItem
    {
        public int Id { get; set; }
        public string Server { get; set; }
        public string Engine { get; set; }
        public string Origin { get; set; }
        public int AlertTypeId { get; set; }
        public int AlertCategoryId { get; set; }
    
        public virtual AlertType AlertType { get; set; }
        public virtual AlertCategory AlertCategory { get; set; }
    }
}
