//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchdogDatabaseAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscalationChainLink
    {
        public int Id { get; set; }
    
        public virtual EscalationChain EscalationChain { get; set; }
        public virtual NotifyeeGroup NotifyeeGroup { get; set; }
        public virtual EscalationChainLink NextLink { get; set; }
        public virtual EscalationChainLink PreviousLink { get; set; }
    }
}
