//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchdogDatabaseAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RuleTemplate()
        {
            this.LastUsedOn = new DateTime(621355968000000000, DateTimeKind.Unspecified);
            this.LastEngine = "n/a";
            this.LastOrigins = "n/a";
            this.LastServers = "n/a";
            this.TemplatedRules = new HashSet<TemplatedRule>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime LastUsedOn { get; set; }
        public string LastEngine { get; set; }
        public string LastOrigins { get; set; }
        public string LastServers { get; set; }
        public int RuleTemplateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplatedRule> TemplatedRules { get; set; }
    }
}
