//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchdogDatabaseAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatedRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplatedRule()
        {
            this.DefaultSeverity = 1;
            this.RuleCategories = new HashSet<RuleCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string RuleCreator { get; set; }
        public string Expression { get; set; }
        public int DefaultSeverity { get; set; }
        public int AlertTypeId { get; set; }
        public string MessageTypeName { get; set; }
        public int SupportCategoryId { get; set; }
        public int RuleTemplateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleCategory> RuleCategories { get; set; }
        public virtual RuleTemplate RuleTemplate { get; set; }
    }
}
