/*Change the value for MessageType_Id as convenient
 *If you're using the message generator and want to match against this rule, then make sure the message Ids match
 */
SET IDENTITY_INSERT dbo.Rules ON;
INSERT INTO dbo.Rules 
(MessageTypeName, Id, Name, [Description], 
Expression, 
AlertTypeId, SupportCategoryId, RuleCreator, DefaultSeverity, Engine, [Server], Origin, [Timestamp])
VALUES
('Test Message Type', 5, 'rule1', 'generated by dbo.Merged.sql', 
'{"condition":"AND","rules":[{"id":"QueueSize","field":"QueueSize","type":"double","input":"text","operator":"between","value":["100","10000"]}]}', 
1, 1, 'a SQL script', 1, 'JCaps', 'some server', 'outer space', '1970-01-01 00:00:00.000');
SET IDENTITY_INSERT dbo.Rules OFF;