SET IDENTITY_INSERT dbo.RuleCategories ON;
INSERT INTO dbo.RuleCategories (Id, Name, [Description]) VALUES (1, 'ruleCategory1', 'generated by dbo.RuleCategories.data.sql');
SET IDENTITY_INSERT dbo.RuleCategories OFF;