SET IDENTITY_INSERT dbo.EscalationChains ON;
INSERT INTO dbo.EscalationChains (Id, Name, [Description], EscalationChainRootLink_Id) VALUES (1, 'testEscalationChain1', 'generated by dbo.EscalationChains.data.sql', 1);
SET IDENTITY_INSERT dbo.EscalationChains OFF;