SET IDENTITY_INSERT dbo.SupportCategories ON;
INSERT INTO SupportCategories (Id, Name, [Description]) VALUES (1, 'senior project team', 'generated by dbo.SupportCategories.data.sql');
SET IDENTITY_INSERT dbo.SupportCategories OFF;