SET IDENTITY_INSERT dbo.AlertTypes ON;
INSERT INTO dbo.AlertTypes (Id, Name, [Description]) VALUES (1, 'test alertType', 'generated by dbo.AlertTypes.data.sql');
SET IDENTITY_INSERT dbo.AlertTypes OFF;