/*Change the value for MessageType_Id as convenient
 *If you're using the message generator and want to match against this rule, then make sure the message Ids match
 */
SET IDENTITY_INSERT dbo.Rules ON;
INSERT INTO dbo.Rules 
(MessageTypeName, Id, Name, [Description], Expression, AlertTypeId, SupportCategoryId, RuleCreator, EscalationChainId, EngineName, Origin, [Server], DefaultSeverity, RuleCategoryId)
VALUES
('Test Message Type', 1, 'rule1', 'generated by dbo.Rules.data.sql', 'QueueSize > 50000', 1, 1, 'a SQL script', 1, 'WatchdogMessageGenerator', 1, 1, 1, 1);
SET IDENTITY_INSERT dbo.Rules OFF;